--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/BetterBan
build-by-default: true
branches:
- master
- Dev
projects:
  BetterBan:
    path: ""
    icon: "icon.gif"
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
      - src: marshall\DiscordWebhookAPI\DiscordWebhookAPI
        version: ^1.0.0
...