--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/BetterBan
build-by-default: true
branches:
- master
projects:
  BetterBan:
    path: ""
    icon: "icon.gif"
    libs:
      - src: https://poggit.pmmp.io/ci/CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        branch: "PM4"
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
