name: BetterBan
version: 3.0.2-1
api: 3.0.0
main: supercrafter333\BetterBan\BetterBan
author: supercrfafter333

permissions:
  BetterBan.admin:
    default: op
    children:
      BetterBan.editban.cmd:
        description: Command permission
        default: op
      BetterBan.banlog.cmd:
        description: Command permission
        default: op
      BetterBan.baninfo.cmd:
        description: Command permission
        default: op
      BetterBan.editipban.cmd:
        description: Command permission
        default: op
      BetterBan.betterban.cmd:
        description: Command permission
        default: op